name: Auto-approve Renovate PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  auto-approve:
    if: contains(github.event.pull_request.labels.*.name, 'renovate')
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
